name: Update Submodules

on:
  workflow_dispatch:  
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout Submodules
        run: |
          git checkout master --recurse-submodules
          git pull

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Auto-Update Submodules"
          git push
